#!/bin/bash

rm -fR ./builds
mkdir builds

cp -R ./ui ./builds/
cd ./builds/

rm -fR ./wifi-connect-hoobs

tar -cvzf ui.tar.gz ./ui/*
mkdir ./wifi-connect-hoobs
mv ./ui ./wifi-connect-hoobs/
mv ./ui.tar.gz ./wifi-connect-hoobs/

tar -cvzf connect.tar.gz ./wifi-connect-hoobs/*

rm -fR ./wifi-connect-hoobs
cd ../
